version: '3.9'
services:
  api-beer:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_HOST: 192.168.254.145
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: beer
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  
networks:
  app_network:

volumes:
  db_data:
